language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hsworkplace11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hsworkplace11/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-806334773511"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"