language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hsworkplace11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hsworkplace11/docker-react npm run test